version: 1
disable_existing_loggers: false

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    filename: ./logs/%(asctime)s.log
    level: INFO
    formatter: simple

formatters:
  simple:
    format: '%(asctime)s | %(levelname)s | [%(name)s.%(funcName)s]: %(message)s'

root:
  level: INFO
  handlers: [file_handler, console]