name: Prevent Push to Master or Develop

on:
  push:
    branches:
      - master
      - develop
      - no-push

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"

      - name: Check if push is to master or develop
        run: |
          if [[ $BRANCH_NAME == "master" || $BRANCH_NAME == "develop" || $BRANCH_NAME == "no-push" ]]; then
            echo "Pushing to $BRANCH_NAME branch is not allowed."
            exit 1
          fi
